name = str(input("Enter your name: "))
num = int(input("Enter an integer: "))
noun1 = str(input("Enter a noun: "))
noun2 = str(input("Enter another noun: "))
noun3 = str(input("Enter a third noun: "))
adjective1 = str(input("Enter an adjective: "))
adjective2 = str(input("Enter another adjective: "))
print ("At {} Pizza Restaurant, they make a {} inch pizza with {}s, {}s, and {}s. The pizza is always served {} and {}.".format(name, num, noun1, noun2, noun3, adjective1, adjective2))
